import fs from 'node:fs';
import process from 'node:process';
import path from 'node:path';
import commandLineArgs from 'command-line-args';

import { ArchitectureFileParser } from './parser.js';

const options = commandLineArgs([
    {
        name: 'input',
        type: String,
    },
    {
        name: 'outputDir',
        type: String,
    },
]);

if (!options.input || !options.outputDir) {
    console.error('[ERROR] Must provide input and output directories!');
    process.exit(1);
}

const writeArchitectureFiles = (architecture) => {
    const outputDir = path.join(options.outputDir, 'archc');
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    const outputFile = path.join(outputDir, `${architecture.name}.h`);

    // prettier-ignore
    const output = `//
// Autogenerated by archc
//

#ifndef ARCHC_${architecture.name.toUpperCase()}_H
#define ARCHC_${architecture.name.toUpperCase()}_H

// Preprocessor Directives
#include <variant>
#include <vector>
#include <city/module/Module.h>
${architecture.preprocessorDirective.join('\n')}

namespace city
{
    // Architecture
    class ${architecture.name} {};
    
    // Instruction Definitions
    ${Object.entries(architecture.instruction)
        .map(([inst, def]) => (
`struct ${architecture.name}${inst}
    {
        ${def.encoding.properties.join('\n\t\t')}
        
        ${architecture.name}${inst}${def.encoding.constructorArgs} ${def.encoding.initializer || ''} 
        {
            ${def.encoding.constructorBody || ''}
        }
    };`)).join('\n\n\t')}
    
    using ${architecture.name}Instruction = std::variant<
        ${Object.keys(architecture.instruction)
        .map(name => `${architecture.name}${name}`)
        .join(',\n\t\t')}
    >;
    
    // Block Specialization
    template<>
    class Block<${architecture.name}> 
    {
        std::vector<${architecture.name}Instruction> instructions_;
        
    public:
        ${Object.entries(architecture.instruction)
            .map(([inst, def]) => (
            `template <typename... Args> 
        [[nodiscard]] city::Value &Insert${inst}(Args... args) 
        {
            this->instructions_.push_back(${architecture.name}${inst}{args...});
        }
            `))
            .join('\n\t\t')}
    };
} // namespace city

#endif // ARCHC_${architecture.name.toUpperCase()}_H
    `;

    fs.writeFileSync(outputFile, output, 'utf-8');
};

const parser = new ArchitectureFileParser(options.input);
const architecture = parser.parse();
writeArchitectureFiles(architecture);
