name: Windows CI

on: [ push, pull_request ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows Latest MSVC
            build_type: Release
            generator: Visual Studio 17 2022
            shell: cmd
            sys: none
            cc: cl
            cxx: cl
          - name: Windows Latest GCC
            build_type: Release
            generator: Ninja
            shell: msys2 {0}
            sys: ucrt64
            env: ucrt-x86_64
            cc: gcc
            cxx: g++
          - name: Windows Latest Clang
            build_type: Release
            generator: Ninja
            shell: msys2 {0}
            sys: clang64
            env: clang-x86_64
            cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2.27.0
        if: ${{ matrix.config.sys != 'none' }}
        with:
          msystem: ${{ matrix.config.sys }}
          install: mingw-w64-${{matrix.config.env}}-${{matrix.config.cc}} ninja cmake

      - shell: msys2 {0}
        name: Configure CMake
        if: ${{ matrix.config.sys != 'none' }}
        run: >
          cmake -B "./build"
          -G "${{ matrix.config.generator }}"
          -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}.exe
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}.exe
          -S .

      - shell: cmd
        name: Configure CMake
        if: ${{ matrix.config.sys == 'none' }}
        run: >
          cmake -B "${{ github.workspace }}/build"
          -G "${{ matrix.config.generator }}"
          -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}.exe
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}.exe
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build "${{ github.workspace }}/build" --config ${{ matrix.config.build_type }}

      - name: Test MSVC
        if: ${{ matrix.config.generator == 'Visual Studio 17 2022'}}
        working-directory: "${{ github.workspace }}/build"
        run: .\Release\city-test.exe

      - name: Test MSYS2
        if: ${{ matrix.config.generator == 'Ninja'}}
        working-directory: "${{ github.workspace }}/build"
        run: .\city-test.exe