name: Windows CI

on: [ push, pull_request ]
jobs:
  build:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows Latest MSVC
            build_type: Release
            cc: cl
            cxx: cl
          - name: Windows Latest GCC
            build_type: Release
            cc: gcc
            cxx: g++
          - name: Windows Latest Clang
            build_type: Release
            cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -B "${{ github.workspace }}/build"
          -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build "${{ github.workspace }}/build" --config ${{ matrix.config.build_type }}

      - name: Test
        working-directory: "${{ github.workspace }}/build"
        run: .\Release\city-test.exe